export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const ADD_COCKTAIL = "ADD_COCKTAIL";
export const UPDATE_COCKTAIL = "UPDATE_COCKTAIL";
export const REMOVE_COCKTAIL = "REMOVE_COCKTAIL";
export const ADD_COMMENT = "ADD_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

export const ADD_REACTION = "ADD_REACTION";
export const REMOVE_REACTION = "REMOVE_REACTION";
